### ISSUE TITLE
How can one build this

### ISSUE THREAD

**Issue by VasilisThePikachu** [vinhowe/Hound#5]
Saw this on Reddit and wanted to try to make you a simple readme but I'm having difficulty building it

I used ```./gradlew build``` in PowerShell but I get this

```> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.spigotmc:spigot:1.16.5-R0.1-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/spigot-1.16.5-R0.1-SNAPSHOT.pom
       - https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/maven-metadata.xml
       - https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/spigot-1.16.5-R0.1-SNAPSHOT.pom
       - https://oss.sonatype.org/content/groups/public/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/groups/public/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/spigot-1.16.5-R0.1-SNAPSHOT.pom
       - https://jitpack.io/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/spigot-1.16.5-R0.1-SNAPSHOT.pom
       - file:/C:/Users/Vasilis/.m2/repository/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/Vasilis/.m2/repository/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/spigot-1.16.5-R0.1-SNAPSHOT.pom
     Required by:
         project :
```

pretty sure it's supposed to check on https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot-api/1.16.5-R0.1-SNAPSHOT/maven-metadata.xml and not https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/maven-metadata.xml but I'm not good with java so idk

**Comment by vinhowe** [comment]
```
- file:/C:/Users/Vasilis/.m2/repository/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/maven-metadata.xml
- file:/C:/Users/Vasilis/.m2/repository/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/spigot-1.16.5-R0.1-SNAPSHOT.pom
```

Have you run [BuildTools](https://www.spigotmc.org/wiki/buildtools/)? Thinking the problem is that your local Maven repository hasn't been set up with Spigot.

**Comment by VasilisThePikachu** [comment]
I haven't, where should i run it with what command?

**Comment by vinhowe** [comment]
Should tell you all you need to know in the link I posted. But I _think_
you can run it from anywhere.

**Comment by MrAusnadian** [comment]
Here's what I did on Windows to build it:
1. Save `BuildTools.jar` to `C:\BuildTools`
2. Run `java -Xmx1024M -jar BuildTools.jar --rev 1.16.5` and wait about 15 minutes
3. Open Command Prompt and change directory to C: (`cd C:`)
4. Run `git clone https://github.com/vinhowe/Hound.git`
5. Change to Hound directory (`cd Hound`)
6. Run `.\gradlew.bat build`
7. Copy `Hound-0.3.0.jar` from `C:\Hound\build\libs` into my servers `plugins` folder

**Comment by vinhowe** [comment]
Looks like once we get @Sxtanna's build.gradle changes in from #4, building should work as described by @MrAusnadian. In the meantime, you can either try using the build.gradle from #4&mdash;though I haven't tested it and he tells me it's not finished&mdash;or configure IntelliJ's Build Artifacts like so:

![image](https://user-images.githubusercontent.com/24789592/112883909-0fcf5800-908c-11eb-8d58-829914ac2f33.png).

**Comment by VasilisThePikachu** [comment]
Yeah it seems like you can now built correctly without intelj. Thanks
